force-app/main/default/objects/General_Configurations__c/General_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>General Configurations</label>
</CustomObject>

force-app/main/default/objects/General_Configurations__c/fields/NumericValue__c.field-meta.xml
<CustomField>
    <fullName>NumericValue__c</fullName>
    <label>NumericValue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/General_Configurations__c/fields/TextValue__c.field-meta.xml
<CustomField>
    <fullName>TextValue__c</fullName>
    <label>TextValue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Utility.cls
public class Utility {
    
    public static String getUniqueId(String FieldName){
        
		General_Configurations__c genConfig = General_Configurations__c.getValues(FieldName);
        String UniqueId = '';
        Integer randomCount = 0;
        do{
            randomCount = Math.round(Math.random()*99);
        } while(randomCount == 0);
        Integer TransactionNo = Integer.valueOf(genConfig.NumericValue__c + randomCount);
        UniqueId = String.valueOf(TransactionNo);
        UniqueId = UniqueId.length()>9?genConfig.TextValue__c+UniqueId.substring(UniqueId.length() - 9):genConfig.TextValue__c+UniqueId;
        genConfig.NumericValue__c = TransactionNo;        
        update genConfig;
        return UniqueId;
    }

}