force-app/main/default/objects/ACME_Transaction_History__b/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Transaction Amount of Customer</description>
    <inlineHelpText>Enter Transaction Amount</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ACME_Transaction_History__b/fields/MerchantName__c.field-meta.xml
<CustomField>
    <fullName>MerchantName__c</fullName>
    <description>Name of the Merchant</description>
    <inlineHelpText>Name of the Merchant</inlineHelpText>
    <label>Merchant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ACME_Transaction_History__b/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>Unique Identification of Transactions.</description>
    <label>Transaction Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ACME_Transaction_History__b/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Transaction Type like Credit or Debit</description>
    <inlineHelpText>Transaction Type must be like Credit or Debit only.</inlineHelpText>
    <label>Type</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/General_Configurations__c/General_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>General Configurations</label>
</CustomObject>

force-app/main/default/objects/General_Configurations__c/fields/NumericValue__c.field-meta.xml
<CustomField>
    <fullName>NumericValue__c</fullName>
    <label>NumericValue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TransactionHistoryController.cls
@RestResource(urlMapping='/api/ACME_Transaction_History__b/*')
global with sharing class TransactionHistoryController
{
    @HttpPost
    global static String doPost() {
        String data = RestContext.request.requestBody.toString();
        List<TransactionHistoryWrapper> transactionDataList = new List<TransactionHistoryWrapper>();
        transactionDataList = (List<TransactionHistoryWrapper>)JSON.deserialize(data, List<TransactionHistoryWrapper>.class);        
        system.debug('>>transactionDataList>> '+transactionDataList);
        
        List<ACME_Transaction_History__b> transactionHistoryList = new List<ACME_Transaction_History__b>();  
        List<Database.SaveResult> saveResults = new List<Database.SaveResult>();
        General_Configurations__c genConfig = General_Configurations__c.getValues('TransactionId');
        String response;
        
        if(!transactionDataList.isEmpty()){
            for(TransactionHistoryWrapper transactionData :transactionDataList){
                ACME_Transaction_History__b transactionHistoryRec = new ACME_Transaction_History__b();
                transactionHistoryRec.ABID__c = transactionData.abid.deleteWhitespace();
                transactionHistoryRec.Amount__c = transactionData.amount;
                transactionHistoryRec.Currency__c = transactionData.transactionCurrency.trim();
                transactionHistoryRec.Transaction_Date__c = Datetime.newInstance(transactionData.transactiondate, transactionData.transactiontime);
                transactionHistoryRec.Type__c = transactionData.transactionType.trim();
                transactionHistoryRec.MerchantABN__c = transactionData.merchantABN;
                transactionHistoryRec.MerchantBSB__c = transactionData.merchantBSB;
                transactionHistoryRec.MerchantName__c = transactionData.merchantName;
                transactionHistoryRec.Transaction_Id__c = genConfig.NumericValue__c+1;
                
                
                transactionHistoryList.add(transactionHistoryRec);
                genConfig.NumericValue__c += 1;
            }
            
        }
                              
        //try{
        if(!transactionHistoryList.isEmpty()){
            saveResults = Database.insertImmediate(transactionHistoryList); 
            update genConfig;
        	system.debug('>>saveResults>>'+saveResults);
            for (Database.SaveResult result : saveResults) {
                if (result.isSuccess()) {
                    response = 'Success';
                }else{
                    response = 'Error';
                    break;
                }
            }
        }
        //}catch(Exception err){
        //    System.debug('Exception!! - '+err.getMessage());
        //}
        
        return response;
	}

}