force-app/main/default/objects/ACME_TransactionHistory__b/fields/MerchantBSB__c.field-meta.xml
<CustomField>
    <fullName>MerchantBSB__c</fullName>
    <description>Merchant BSB</description>
    <inlineHelpText>Merchant BSB</inlineHelpText>
    <label>Merchant BSB</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ACME_TransactionHistory__b/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <description>Transaction Date</description>
    <inlineHelpText>Date of Transaction.</inlineHelpText>
    <label>Transaction Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Financial_Accounts__c/Financial_Accounts__c.object-meta.xml
<CustomObject>
    <description>Object to store Financial Accounts of Customers.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Accounts__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Account Number of Customer</description>
    <inlineHelpText>Account Number of Customer</inlineHelpText>
    <label>Account Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financial_Accounts__c/fields/Acme_Bank_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Acme_Bank_Unique_ID__c</fullName>
    <description>Acme Bank Unique ID of Financial Accounts</description>
    <externalId>true</externalId>
    <label>Acme Bank Unique ID (ABID)</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Financial_Accounts__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Customer Address</description>
    <inlineHelpText>Enter Address</inlineHelpText>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Financial_Accounts__c/fields/Balance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Balance_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Calculated Balance Amount of customers</description>
    <label>Balance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Accounts__c/fields/Balance_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Balance_Calculation__c</fullName>
    <label>Balance Calculation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
                <default>true</default>
                <label>Calculated</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Accounts__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Customer Email address</description>
    <inlineHelpText>Enter Email address</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Financial_Accounts__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Account State of Customers</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Financial_Accounts__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Customer Phone Number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Financial_Accounts__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Customer Types</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spending</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/General_Configurations__c/General_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>General Configurations</label>
</CustomObject>

force-app/main/default/objects/General_Configurations__c/fields/NumericValue__c.field-meta.xml
<CustomField>
    <fullName>NumericValue__c</fullName>
    <label>NumericValue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/General_Configurations__c/fields/TextValue__c.field-meta.xml
<CustomField>
    <fullName>TextValue__c</fullName>
    <label>TextValue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/**********************************************************************************************
 * @Class name:     TestDataFactory
 * @description:    Data Factory for Test Classes.
 * @testclass:      FinancialAccountTrigger_Test and TransactionHistoryController_Test
 * HISTORY *
 ===========
 Auther         Date                Comment
***********************************************************************************************/

public class TestDataFactory {

    public static General_Configurations__c  creategenralConfiguration(){
        
        General_Configurations__c genConfig = new General_Configurations__c(Name = 'ABID',
                                                                            FieldName__c = 'Acme_Bank_Unique_ID__c',
                                                                            isActive__c = true,
                                                                            NumericValue__c=100000001,
                                                                            TextValue__c='ABK'
                                                                           );
        insert genConfig;
        General_Configurations__c genConfigTranId = new General_Configurations__c(Name = 'TransactionId',
                                                                            FieldName__c = 'Transaction_Id__c',
                                                                            isActive__c = true,
                                                                            NumericValue__c=100001
                                                                           );
        insert genConfigTranId;
        return genConfig;
    }
    
    public static Financial_Accounts__c createFinancialAcc(String ABID){
        
        Financial_Accounts__c finantialAcc = new Financial_Accounts__c();
        finantialAcc.Account_Number__c = 123456789;
        finantialAcc.Acme_Bank_Unique_ID__c = ABID;
        finantialAcc.Address__c = 'Sydney 2000, NSW, Australia'; 
        finantialAcc.Balance_Amount__c = 0;
        finantialAcc.Email__c = 'sam.test@test.com';
        finantialAcc.IsActive__c = true;
        finantialAcc.Name = 'Sam Test';
        finantialAcc.Phone__c = '0411111111';
        finantialAcc.Type__c = 'Savings';
        finantialAcc.Balance_Calculation__c = 'Pending';
        insert finantialAcc;
        return finantialAcc;
    }
    public static List<Financial_Accounts__c> createFinancialAcc(Integer count){
        
        List<Financial_Accounts__c> finantialAccounts = new List<Financial_Accounts__c>();
        
        for(Integer i=0; i<count; i++){
            Financial_Accounts__c finantialAcc = new Financial_Accounts__c();
            finantialAcc.Account_Number__c = Integer.valueOf(String.ValueOf(System.Now()).replaceAll('[-: ]','').substring(3, 12));
            finantialAcc.Address__c = 'Sydney 2000, NSW, Australia';
            finantialAcc.Balance_Amount__c = 0;
            finantialAcc.Email__c = 'sam'+count+'.test@test.com';
            finantialAcc.IsActive__c = true;
            finantialAcc.Name = 'Sam'+count+' Test';
            finantialAcc.Phone__c = '04111111'+count+count;
            finantialAcc.Type__c = 'Savings';
            
            finantialAccounts.add(finantialAcc);
        }
        Database.insert(finantialAccounts);
        return finantialAccounts;
    }
    public static List<ACME_TransactionHistory__b> createTransactionHistory(Integer count, String ABID){
        
        List<ACME_TransactionHistory__b> transactionHistoryList = new List<ACME_TransactionHistory__b>();
            
        for(Integer i=0; i<count; i++){
            ACME_TransactionHistory__b transactionHistoryRecds = new ACME_TransactionHistory__b();
            transactionHistoryRecds.ABID__c = ABID;
            transactionHistoryRecds.AccountNumber__c = Integer.valueOf(String.ValueOf(System.Now()).replaceAll('[-: ]','').substring(3, 12));
            transactionHistoryRecds.Amount__c = 150.25;
            transactionHistoryRecds.Currency__c = 'AUD';
            transactionHistoryRecds.MerchantABN__c = 123456789;
            transactionHistoryRecds.MerchantBSB__c = 123456;
            transactionHistoryRecds.MerchantName__c = 'Beau Flowers';
            transactionHistoryRecds.Type__c = 'debit';
            transactionHistoryRecds.Transaction_Date__c = Datetime.newInstance(2021,1,10);
            transactionHistoryRecds.Transaction_Id__c = Integer.ValueOf(Utility.getUniqueId('TransactionId'));
            
            transactionHistoryList.add(transactionHistoryRecds);
        }
        //Database.insert(transactionHistoryList);
        return transactionHistoryList;
    }
}