force-app/main/default/objects/ACME_TransactionHistory__b/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <description>Transaction Date</description>
    <inlineHelpText>Date of Transaction.</inlineHelpText>
    <label>Transaction Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Financial_Accounts__c/Financial_Accounts__c.object-meta.xml
<CustomObject>
    <description>Object to store Financial Accounts of Customers.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Accounts__c/fields/Acme_Bank_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Acme_Bank_Unique_ID__c</fullName>
    <description>Acme Bank Unique ID of Financial Accounts</description>
    <externalId>true</externalId>
    <label>Acme Bank Unique ID (ABID)</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Financial_Accounts__c/fields/Balance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Balance_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Calculated Balance Amount of customers</description>
    <label>Balance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Accounts__c/fields/Balance_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Balance_Calculation__c</fullName>
    <label>Balance Calculation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
                <default>true</default>
                <label>Calculated</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Accounts__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Customer Types</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spending</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProcessBuilderController.cls
public class ProcessBuilderController {
	
    @InvocableMethod
    public static void FinancialAccountProcessBuilder(List<Financial_Accounts__c> financialAccountList){
        
        Map<String, Id> abidIds = new Map<String, Id>();
        for(Financial_Accounts__c financialAcc :financialAccountList){
            if(financialAcc.Balance_Calculation__c == 'Pending' && financialAcc.Acme_Bank_Unique_ID__c != null){
                abidIds.put(financialAcc.Acme_Bank_Unique_ID__c, financialAcc.Id);
            }
        }
        CalculateTransactionBalance(abidIds);
    }
    @future
    public static void CalculateTransactionBalance(Map<String, Id> abidIds){
        
        List<Financial_Accounts__c> updatedFinancialAccs = new List<Financial_Accounts__c>();
        Map<Id,Decimal> mapCalculateAmt = new Map<Id,Decimal>();
        for(ACME_TransactionHistory__b tranHistory : [SELECT Id, createddate, ABID__c, Amount__c, Transaction_Date__c, Type__c, Transaction_Id__c FROM ACME_TransactionHistory__b  WHERE ABID__c IN:abidIds.keySet() LIMIT 40000]){
            if(mapCalculateAmt.containsKey(abidIds.get(tranHistory.ABID__c))){
                Decimal currentCalculatedvalue = mapCalculateAmt.get(abidIds.get(tranHistory.ABID__c));
                Decimal calculatedvalue = tranHistory.Type__c == 'debit'?currentCalculatedvalue + tranHistory.Amount__c:currentCalculatedvalue - tranHistory.Amount__c;
                mapCalculateAmt.put(abidIds.get(tranHistory.ABID__c), calculatedvalue);
            }else{
                Decimal calculatedvalue = tranHistory.Type__c == 'debit'?0.00 + tranHistory.Amount__c:0.00 - tranHistory.Amount__c;
                mapCalculateAmt.put(abidIds.get(tranHistory.ABID__c), calculatedvalue);
            }
        }
        for(Id finAccRec:abidIds.values()){
            if(mapCalculateAmt.containsKey(finAccRec)){
                Financial_Accounts__c updatedfinAccRec = new Financial_Accounts__c(Id=finAccRec);
                updatedfinAccRec.Balance_Amount__c = mapCalculateAmt.get(finAccRec);
                updatedfinAccRec.Balance_Calculation__c = 'Calculated';
                
                updatedFinancialAccs.add(updatedfinAccRec);
            }
        }
        system.debug('>>updatedFinancialAccs>>'+updatedFinancialAccs);
        //try{
        	if(!updatedFinancialAccs.isEmpty())
            Database.update(updatedFinancialAccs);
        //}catch(){
            
        //}
    }
}