force-app/main/default/objects/Financial_Accounts__c/Financial_Accounts__c.object-meta.xml
<CustomObject>
    <description>Object to store Financial Accounts of Customers.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Accounts__c/fields/Acme_Bank_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Acme_Bank_Unique_ID__c</fullName>
    <description>Acme Bank Unique ID of Financial Accounts</description>
    <externalId>true</externalId>
    <label>Acme Bank Unique ID (ABID)</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/General_Configurations__c/General_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>General Configurations</label>
</CustomObject>

force-app/main/default/classes/FinancialAccountTrigger_Test.cls
@isTest
public class FinancialAccountTrigger_Test {
	
    @isTest
    public static void generateABID_Test(){
        //Test Setup
        General_Configurations__c genConfig =  TestDataFactory.creategenralConfiguration();
            
        //Test Scenario
        Test.startTest();
        Financial_Accounts__c financialAccRec = TestDataFactory.createFinancialAcc();
        system.assert(financialAccRec.Acme_Bank_Unique_ID__c != null || financialAccRec.Acme_Bank_Unique_ID__c != '');
        Test.stopTest();
    }
    @isTest
    public static void generateABID_TestBulk(){
        //Test Setup
        General_Configurations__c genConfig =  TestDataFactory.creategenralConfiguration();
            
        //Test Scenario
        Test.startTest();
        List<Financial_Accounts__c> financialAccRec = TestDataFactory.createFinancialAcc(500);
        List<Financial_Accounts__c> CountRec = [Select id from Financial_Accounts__c Where Acme_Bank_Unique_ID__c != ''];
        system.assert(CountRec.size() == 500);
        Test.stopTest();
    }
}