force-app/main/default/objects/Financial_Accounts__c/Financial_Accounts__c.object-meta.xml
<CustomObject>
    <description>Object to store Financial Accounts of Customers.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Accounts__c/fields/Acme_Bank_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Acme_Bank_Unique_ID__c</fullName>
    <description>Acme Bank Unique ID of Financial Accounts</description>
    <externalId>true</externalId>
    <label>Acme Bank Unique ID (ABID)</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/General_Configurations__c/General_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>General Configurations</label>
</CustomObject>

force-app/main/default/objects/General_Configurations__c/fields/NumericValue__c.field-meta.xml
<CustomField>
    <fullName>NumericValue__c</fullName>
    <label>NumericValue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/General_Configurations__c/fields/TextValue__c.field-meta.xml
<CustomField>
    <fullName>TextValue__c</fullName>
    <label>TextValue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FinancialAccountTriggerHandler.cls
public without sharing class FinancialAccountTriggerHandler {
    
    public static void generateABID(List <Financial_Accounts__c> financialAccounts){
        List<Financial_Accounts__c> updatedFinancialAccs = new List<Financial_Accounts__c>();
        
		General_Configurations__c  genConfig = General_Configurations__c.getValues('ABID');
        for(Financial_Accounts__c accountRec :financialAccounts){
            String TransactionId = '';
            Integer randomCount = 0;
            do{
                randomCount = Math.round(Math.random()*99);
            } while(randomCount == 0);

            Integer TransactionNo = Integer.valueOf(genConfig.NumericValue__c + randomCount);
            if(accountRec.Acme_Bank_Unique_ID__c == null){
                TransactionId = String.valueOf(TransactionNo);
            }	
            accountRec.Acme_Bank_Unique_ID__c = TransactionId.length()>9?genConfig.TextValue__c+TransactionId.substring(TransactionId.length() - 9):genConfig.TextValue__c+TransactionId;
            updatedFinancialAccs.add(accountRec);
      
            genConfig.NumericValue__c = TransactionNo;
            
        }
        update genConfig;
    }
}